### ISSUE TITLE
finch can not login

### ISSUE THREAD

**Issue by nancom** [runfinch/finch#126]
I use finch on Apple M1 (Ventura)
When i try to use command 

$ finch login 

system  show prompt for login 
Enter Username: nancom
Enter Password:
WARNING: Your password will be stored unencrypted in /Users/panupongchantaklang/.finch/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

FATA[0005] error saving credentials: mkdir /Users/panupongchantaklang: permission denied

** 
because i change my default user folder from  panupongchantaklang -> nancom  when i new install my operating system

any config for change /Users/panupongchantaklang/ --> /Users/nancom/

**Comment by pendo324** [comment]
[This `updateEnvironment` function](https://github.com/runfinch/finch/blob/main/pkg/config/nerdctl_config_applier.go#L64-L80) seems to be the cause of the bug.

Right now, on every boot, it just checks your VM user's `.bashrc` file to see if it contains `export DOCKER_CONFIG` (this is the variable that sets the `config.json` path), instead of checking if it contains the variable _and_ if the variable is set to the current user's `$HOME` directory.

This is an oversight in our code, mostly because the `$HOME` directory changes very infrequently.

You may have other issues if you change your home directory, or if you change your user between when you initialize your VM and when you try using Finch (we haven't really tested this scenario much).

If you want a workaround until the fix is released, you can run `finch vm stop && finch vm remove` and then `finch vm init` with your new user.
