### ISSUE TITLE
Detecting whether a script is running inside guest

### ISSUE THREAD

**Issue by pose** [runfinch/finch#166]
**What is the problem you're trying to solve?.**
I'm writing a shell script and I want to determine whether I'm insider a container or not. I was achieving this in bash by doing:

```
if [[ ! -f /.dockerenv ]]; then
  echo "Executing in host";
else
  echo "Executing in guest";
fi
```

However, it seems that `.dockerenv` is Docker-implementation specific.

**Describe the feature you'd like**
How can I determine whether I'm running inside a container? Thanks!

**Additional context**

I got the instructions on how to do this detection from here: https://stackoverflow.com/questions/20010199/how-to-determine-if-a-process-runs-inside-lxc-docker

**Comment by estesp** [comment]
As the number of available container runtimes has grown, answering the question "am I running in a container?" has gotten quite a bit more complicated. One shining example is the program [`amicontained`](https://github.com/genuinetools/amicontained) from Jess, who worked on the original Docker engine project for many years.

You can see from the laundry list of attempts to determine containment (some bpf based, some based on states of various namespaces, looking for certain strings, etc.) there is no "one way" to determine if your program is inside a container or not. `/.dockerenv` was an easy hack for many years, not purposefully, but just because it was reliably there.

Given that, I think you may have to look at the problem from a different angle and determine why you need to know if you are in a container, and if there is a better way to share that detail in the container's environment rather than potentially relying on something that changes over time or differs between runtime environments.

**Comment by AkihiroSuda** [comment]
This may work
```bash
if [ "$(readlink -v /proc/self/ns/pid)" = 'pid:[4026531836]' ]; then 
  echo "not a container"
else
  echo "probably a container"
fi
```

https://github.com/torvalds/linux/blob/c1649ec55708ae42091a2f1bca1ab49ecd722d55/include/linux/proc_ns.h#L43-L48

**Comment by pose** [comment]
@AkihiroSuda Thanks! Yes, that worked for my script, but not for interactive shell sessions.

>  I think you may have to look at the problem from a different angle and determine why you need to know if you are in a container, and if there is a better way to share that detail in the container's environment rather than potentially relying on something that changes over time or differs between runtime environments.

Thanks. My use case is that I'm executing a script that's supposed to run both on the host and the container. When I'm in the host, it should create a container and execute itself there.

I'm realising as I'm writing this is that I can pass `-e IN_GUEST=1` to `finch run ...` and check for that variable to be set. That's basically [all I needed for my script](https://github.com/pose/dotfiles/blob/main/test/run-test.sh#L17).

Thanks!

**Comment by pose** [comment]
BTW, I'm closing this ticket since I managed to do what I wanted to. Thanks!
