### ISSUE TITLE
Env variables passing not compatible with docker command

### ISSUE THREAD

**Issue by bruecktech** [runfinch/finch#35]
**What is the problem you're trying to solve?.**
I use finch as a docker alias
```
alias docker=finch
```

Env variables in Docker can be passed just with the name and then the value will be passed automatically
```
❯ export FOO=bar
❯ docker run -e FOO ubuntu env
HOME=/root
FOO=bar
HOSTNAME=809ed84fc40f
```

But with finch I have to pass the value explicitly. In the output the FOO variable is missing

```
❯ alias docker=finch
❯ export FOO=bar
❯ docker run -e FOO ubuntu env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOME=/root
```

**Describe the feature you'd like**
Allow passing variables with the name only, so that `finch run` is compatible to the `docker run` command and can be used as a drop-in replacement

**Comment by estesp** [comment]
The base functionality of correctly handling `-e {SOME_ENV_VAR}` was fixed in nerdctl v1.1.0, and with Finch v0.2.0, our lima update includes the updated nerdctl release with the fix. However, now that `-e` works, there is still an issue with passing the host (macOS) environment settings into the Lima VM. We can keep this issue open until we solve that second issue (working on it now)
